# Generated by Django 5.2 on 2025-06-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=100)),
                ('nota_atividade', models.IntegerField(default=0)),
                ('nota_trabalho', models.IntegerField(default=0)),
                ('nota_prova', models.IntegerField(default=0)),
                ('media', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
